### ISSUE TITLE
Teacher review week 4

### ISSUE THREAD

**Issue by Tyler929** [Archkitten/python_experts#24]

**Comment by jm1021** [comment]
Pair on ASCII.  Technical  job for Tyler and William to add images. David no assignments.  .9/1.0

**Comment by katiehickman** [comment]
### **Planning for team (by Mr. M):**
.9/1

### **Individual Work/Technicals:**
(0.75 was taken off if there were no technical commits)

_Aidan 2/2,_ you did all of the binary technical commits and notes in the journal, but maybe add a link to our personal journal
_Tyler 1.5/2,_ you have a very minimal technical commit (greet) and are only working on the READme, but your journal shows work on notes for the week 
_William 1.25/2,_ you have nice journal notes, but for your commits I only see renamed files/embedding images and images that you dragged into the files. no technical code
_Arch: 2/2,_ you have one technical commit in games.html and one thing in binary.html and your notes look good
_David: 1.25/2,_ you have no technical code and there's only images being added, but you have notes in your journal

### **Team Technicals:**
_1.5/2,_ for your READme because none of the links in your evidence table work except Tyler's link and there's a large paragraph that should be in a table.

Your video had really nice highlights, but when I checked the code commits it seemed like Aidan did most of the technical code, which was the goal of this week.

**Comment by jm1021** [comment]
Aiden 4.4
Tyler 3.9
William 3.65
David 3.64
Arch 4.4
