### ISSUE TITLE
Teacher review (PRESENTATION)

### ISSUE THREAD

**Issue by Tyler929** [Archkitten/python_experts#44]

**Comment by kamyamah** [comment]
I liked the games especially the rock paper scissors It shows a great example of conditional statements.

**Comment by YashShah138** [comment]
I liked the grass background being implemented throughout the website, but I think you could improve the user interface.

**Comment by Isaac-Le** [comment]
The page could be more complete but I like the idea and the games that you are adding into the website and the visual appeal it has. I don't know if sleeping simulator is really a game but it does look good and it changes the DOM.

**Comment by kiannp44** [comment]
The background seems very off-setting compared to the function of the website, grass doesn't really correlate to gaming. I also really like the formatting of the games. Well done!

**Comment by MaBoinjd** [comment]
I like your layout for all the games. One suggestion is to create new pages in your website with the games. Overall it is well made.

**Comment by tonyhieu** [comment]
I really liked the concept and the layout of your page. One suggestion is to have the rock paper scissors game show up when you click on the button for it instead of taking you to a new web page.

**Comment by danaylevy2004** [comment]
Things I liked:
- The technicals has its own bit of humor to it. I especially liked the Patrick function. The games are interesting and I thought the rock paper scissor simulator was also unique. I also like the concept.
Things to improve on: 
- Provide more backgrounds. I thought the grass background was a bit repetitive.

**Comment by Pitsco** [comment]
The website although may look basic, it starts off with a grasping introduction of what the website is mainly about. I like how you guys implemented it in games such as rock paper scissors and other minilabs. The only thing that I would fix is the repetitive background that doesn't look interesting to the visitor.

**Comment by LindaLiu1202** [comment]
The website is really organized. I really like how they have all these games in their website! I like the rock paper scissor game, and it's a great example of conditional statements. I really like the sleeping simulator; it's really cute!! One suggestion is that maybe you can change the grass background since it's a little repetitive.

**Comment by mahimak19** [comment]
I really like the games that you coded, like the rock paper scissors especially. The sleep simulator was also very creative and funny, and I like how you incorporated binary to make the game. I also like your layout. It looks very clean and organized. One thing you can work on is making the rock paper scissors game to actually function on the page instead of a separate popup.
